	<div style="text-align: center;align-content: center;margin: 30px;">
		 	<form action= "{{login}}" method="post">
			账&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号：<input type="text" name="userName" value="">		
			<br />
			密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：<input type="password" name="userPassword" value="">	
			<br />
			<br />
			<input id='login'  type="submit" value="登录"> 
			</form>
	</div>

	<div>
		<ul>
			{% for name,value in robs  if name != 2 %}
				<li>
            		name : {{ name|e }}
            		value : {{ value['name']|e }}
            		index : {{ loop.index0}}
      		    </li>
			{% endfor %}
		</ul>
	</div>
		
<script type="text/javascript">

</script>