
	<div style="width: 100%;text-align: right;">
	   <a href="{{login}}">登录</a>
	   <a href="{{register}}">注册</a>
	</div>

	<div style="text-align: center;align-content: center;">
		 	<form action= "{:url('index/Index/login')}" method="post">
			账&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号：<input type="text" name="userName" value="">		
			<br />
			
			密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;保：<input type="text" name="userName" value="">		<br />
			答&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;案：<input type="text" name="answer" value="">			<br />
			密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：<input type="password" name="password" value="">		<br />	
			密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：<input type="password" name="password2" value="">		<br />	

			<br />
			<input id='login'  type="submit" value="修改">
			<input type="button" value="取消" onclick="javascript :history.back(-1);">
			</form>
	</div>
<script type="text/javascript">

</script>
